name: Build and Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'   # Runs every week on Mondays at midnight
  workflow_dispatch:      # Runs on user's request

jobs:
  build:
    runs-on: windows-latest   # Set to the latest available Windows
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: |
        pip install pyinstaller==4.5 pyyaml==6.0 lxml==4.6.3 PyQt5==5.15.4
        # It's recommended to install all dependencies in one pip command to avoid version compatibility issues

    - name: Run installation script
      run: |
        .\installResources.ps1
      shell: PowerShell

    - name: Find project.py
      run: |
        echo "Looking for project.py..."
        Get-ChildItem -Recurse -Filter project.py | ForEach-Object { Write-Output $_.FullName }
      shell: pwsh

    - name: Build executable
      run: |
        pyinstaller.exe --onefile --noconsole ./project.py
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: data-converter
        path: dist/project.exe





